from pydantic import BaseModel, Field


class GeneratedScript(BaseModel):
    """A Python script generated by the script-generation agent (§2.1).

    The script uses the CRUD helpers reused from ``uwazi_agent`` (create/update/
    delete/publish entities, create_relationships, query_entities) — never
    free-form network or DB code. The agent validates it against dummy entities
    in the real instance before it touches real data (§2.7).
    """

    python_code: str = Field(min_length=1, description="The generated Python script body.")
    description: str | None = Field(default=None, description="Short human-readable intent of the script.")
