MODEL = "deepseek-v4-flash:cloud"
ENTITIES_LIMIT_FOR_LLM_MODEL = 5
PYTHON_SCRIPT_OUTPUT_CHARACTERS_LIMIT = 2500
REQUEST_LIMIT = 20
OLLAMA_BASE_URL = "https://ollama.com/v1"

PUBLISH_CHUNK_SIZE = 50
PUBLISH_RETRY_ON_429 = True
